NETQ_PSTN_TOE_ACTIVE=NETQ.PSTN.TOE_ACTIVE: 10.162.204.XXX
NETQ_PSTN_ROT_ACTIVE=NETQ.PSTN.ROT_ACTIVE: 10.162.218.102
NETQ_VOIP_OPERATOR=LAB_PT_COM
NETQ_GPON_HGW_FIBER=GS1000GH,GR241AG,GR141DG,XSR151DK,GE141IG
# Configurações JVM/Aplicações
NETQPTC_JAVA_OPTS="-Xmx256M -Xms256M -Xss256K"
NETQ_BACKEND_PRIVATE_THREADS=50
NETQPTC_QUARTZ_INSTANCE_NAME=NetqPTCPersistenceScheduler_10.162.218.102
# Configurações AKKA
NETQ_AKKA_PLUGIN_NOTIFICATION=NETQ.AKKA.PLUGIN_NOTIFICATION: 20
NETQ_AKKA_PLUGIN_HTTPCLIENTPLUGIN=NETQ.AKKA.PLUGIN_HTTPCLIENTPLUGIN: 30
NETQ_AKKA_PLUGIN_SAPAPLUGIN=NETQ.AKKA.PLUGIN_SAPAPLUGIN: 80
NETQ_AKKA_PLUGIN_NETWINPLUGIN=NETQ.AKKA.PLUGIN_NETWINPLUGIN: 20
NETQ_AKKA_PLUGIN_NAEMPLUGIN=NETQ.AKKA.PLUGIN_NAEMPLUGIN: 5
NETQ_AKKA_PLUGIN_AMPLUGIN=NETQ.AKKA.PLUGIN_AMPLUGIN: 30
NETQ_AKKA_PLUGIN_TIBCO=NETQ.AKKA.PLUGIN_TIBCO: 20
NETQ_AKKA_PLUGIN_NA=NETQ.AKKA.PLUGIN_NA: 10
NETQ_AKKA_PLUGIN_HTTP=NETQ.AKKA.PLUGIN_HTTP: 30
NETQPTC_AKKA_GLOBAL_ACTOR=NETQPTC.AKKA.GLOBAL_ACTOR: 50
# Configurações Databases
NETQ_MONGODB_URL="mongodb://{{ NETQ.MONGODB.USER }}:{{ NETQ.MONGODB.PASSWORD }}@{{ NETQ.MONGODB.HOST }}/netq?maxIdleTimeMS=60000"
NETQ_DB_URL=jdbc:oracle:thin:@//cxq01vmc01-scan.telecom.pt:1565/QNETQV4CP-SRV
NETQ_DB_USERNAME=netq
NETQ_DB_PASSWORD=Netq_QA#_2021
NETQ_DB_POOLSIZE=10
IN.DB.DRIVER=oracle.jdbc.OracleDriver
IN.DB.URL=""
IN.DB.USERNAME=GEREX_IN
IN.DB.PASSWORD=gerex
IN.DB.SCHEMA=GEREX_IN
IN.DB.POOLSIZE=""
IN.DB.DIALECT=""
# Configurações CRM
NETQ_PTC_CRM_CRON="0 0 22 1/1 * ? *"
NETQ_PTC_CRM_HOST=10.162.205.100
NETQ_PTC_CRM_DIR=/qeftlgtr/
NETQ_PTC_CRM_USER=qcrm2gerex
NETQ_PTC_CRM_PASSWORD=lmeG3bUof2
# Configurações Logger
LOGGING_LEVEL=WARN
LOGGING_LEVEL_ASF=
LOGGING_LEVEL_NETQ=DEBUG
LOGGING_CONSOLE_LEVEL=DEBUG
LOGGING_GELF_PROTOCOL=UDP
LOGGING_GELF_HOST=10.18.128.37
LOGGING_GELF_PORT=12201
LOGGING_GELF_LEVEL=DEBUG
LOGGING_GELF_NULL_DELIMITER=False
LOGGING_GELF_COMPRESSION=GZIP
LOGGING_APP_ENVIRONMENT=meo-ptc-qa
# Configurações de serviços externos
NETQ_MPLS_NAT_URL=http://ptesb-qa.telecom.pt:13100/PTP/25_CUSTOMER/CustomerOrder/Services/3.0/create
NETQ_QUALIFIER_TIBCO_URL=http://ptesb-qa.telecom.pt:13100/PTP/25_RESOURCE/ResourceNetwork/Services/1.0/getViabilityWithMeasures
# Configurações SAPA
NETQ_SAPA_URL=http://10.162.109.28/interface_generica/query_xml2_v2.asp
NETQ_SAPA_URL_TIBCO_START=http://ptesb-qa.telecom.pt:13000/PTP/25_SERVICE/ServiceTechniqueClasse/Services/1.0/start
NETQ_SAPA_URL_TIBCO_END=http://ptesb-qa.telecom.pt:13000/PTP/25_SERVICE/ServiceTechniqueClasse/Services/1.0/end
# Configurações ALTAIA
NETQ_ALTAIA_URL=http://10.114.222.154:9095/altaia/api/nbi
NETQ_ALTAIA_CLIENT_ID=nbi-netq
NETQ_ALTAIA_CLIENT_SECRET=NetQ#2020
# Configurações STB PM
NETQ_STB_PM_URL=http://10.112.181.10
NETQ_STB_PM_AUTHENTICATION=Basic dGVzdDoyUUVreUZIeFBzQTQ=
# Configurações AM
NETQ_AM_URL="https://amqa.telecom.pt"
NETQ_AM_TOKEN="Basic bmV0cS1xYTpBUU4zdFEyMDIxISEh"
# Configurações SIGNET
NETQ_FAULT_URL=http://signet-qa-fe.telecom.pt/SignetService/SignetAvarias/1.0/ServiceAvariaComum.svc
NETQ_FAULT_URL_MOBILE=http://signet-qa-fe.telecom.pt/SignetMobileService/ServiceSignetMobile.svc
# Configurações INVENTORY
NETQ_INVENTORY_GSU_QUERY_USERNAME=http://ptesb-qa.telecom.pt:13000/PTP/25_PRODUCT/ProductBaseProduct/Services/2.0/getDetailsByServiceNumber
NETQ_INVENTORY_ONT_UPDATE=http://ptesb-qa.telecom.pt:13300/PTP/25_RESOURCE/ResourceNetworkIS/Services/1.0/pairingNotification
NETQ_INVENTORY_SERVICE_QUERY=http://ptesb-qa.telecom.pt:13000/PTP/25_SERVICE/ServiceMeo/Services/1.1/getState
NETQ_INVENTORY_CIMS_SERVICE_QUERY=http://ptesb-qa.telecom.pt:13000/PTP/25_PRODUCT/ProductBaseProduct/Services/1.0/getInstalationDetail
NETQ_INVENTORY_SIGNET_OSP=http://10.162.126.195/SignetCadastroLrWS/SignetCadastroLrWSImpl.svc
NETQ_MOBILE_INVENTORY_MOBILE_GET_INFO_URL=http://ptesb-qa.telecom.pt:13000/PTP/25_PRODUCT/ProductBaseProduct/Services/1.1/getDetailsLight
NETQ_MOBILE_INVENTORY_MOBILE_SIM_CARD_URL=http://ptesb-qa.telecom.pt:13000/PTP/25_SERVICE/ServiceCFServiceGSM/Services/2.0/getInfo
# Configurações MOBILE
NETQ_MOBILE_TRAFFIC_SUMMARY_URL=http://ptesb-qa.telecom.pt:13000/PTP/25_PRODUCT/ProductProduct/Services/1.0/getWalletAndUsage
NETQ_MOBILE_TRAFFIC_DETAIL_URL=http://ptesb-qa.telecom.pt:13000/PTP/25_PRODUCT/ProductUsage/Services/1.0/getDetails
NETQ_MOBILE_TERMINAL_INFO_URL=https://mobiledevices.telecom.pt/online/BDTerminais/mremote.php?input=x&output=y
NETQ_MOBILE_TERMINAL_INFO_READ=30
NETQ_MOBILE_TERMINAL_INFO_CONNECT=10
NETQ_MOBILE_VOICEMAIL_INFO_URL=http://ptesb-qa.telecom.pt:13000/PTP/25_SERVICE/ServiceRFSCaixaVM/Services/1.0/getInfo
NETQ_MOBILE_VOICEMAIL_INFO_READ=30
NETQ_MOBILE_VOICEMAIL_INFO_CONNECT=10
NETQ_MOBILE_PRODUCT_SERVICES_URL=http://ptesb-qa.telecom.pt:13000/PTP/25_PRODUCT/ProductBaseProduct/Services/2.2/getPortfolio
NETQ_MOBILE_PRODUCT_SERVICES_READ=30
NETQ_MOBILE_PRODUCT_SERVICES_CONNECT=10
NETQ_MOBILE_EVENT_URL=NOT_AVAILABLE_FUTURE
NETQ_MOBILE_EVENT_READ=30
NETQ_MOBILE_EVENT_CONNECT=10
NETQ_MOBILE_EVENT_QOS_URL=NOT_AVAILABLE_FUTURE
NETQ_MOBILE_EVENT_QOS_READ=30
NETQ_MOBILE_EVENT_QOS_CONNECT=10
NETQ_MOBILE_DIAG_URL=http://ptesb-qa.telecom.pt:13000/PTP/25_COMMON/CommonConfrontation/Services/1.0/getbyNumeroCFS
NETQ_MOBILE_DIAG_READ=30
NETQ_MOBILE_DIAG_CONNECT=10
NETQ_MOBILE_FIX_URL=http://ptesb-qa.telecom.pt:13000/PTP/25_COMMON/CommonConfrontation/Services/1.0/fixError
NETQ_MOBILE_FIX_READ=30
NETQ_MOBILE_FIX_CONNECT=10
# Configurações MSIPTV
NETQ_MSIPTV_URL_RESET_CREDIT=http://ptesb-tst3.telecom.pt:11100/PTP/25_SERVICE/ServiceServiceIPTV/Services/1.0/resetCreditLimit
NETQ_MSIPTV_URL_CLOUD_DVR_SET=http://ptesb-qa.telecom.pt:13000/PTP/25_SERVICE/ServiceServiceIPTV/Services/1.0/update
NETQ_MSIPTV_SDB_FIX_URL=https://pre-release.services.bk.sapo.pt/OTT/Services/Subscription/Synchronize
NETQ_MSIPTV_SDB_FIX_TIMEOUT=30
NETQ_MSIPTV_SDB_FIX_TOKEN="ESB Token=01.7dV0OPTOb_qVbm0kpIMlgA"
NETQ_MSIPTV_SDB_QUERY_STORAGE_URL=https://pre-release.services.bk.sapo.pt/OTT/Services/User/Recordings/GetStorageInfo
NETQ_MSIPTV_SDB_QUERY_STORAGE_TIMEOUT=30
NETQ_MSIPTV_SDB_QUERY_STORAGE_TOKEN="ESB Token=01.7dV0OPTOb_qVbm0kpIMlgA"
NETQ_NETWIN_INVENTORY_QUERY_NETWORK_ACCESS=http://ptesb-qa.telecom.pt:13000/PTP/25_RESOURCE/ResourceNetwork/Services/1.0/getAccessNetwork
NETQ_NETWIN_INVENTORY_QUERY_LOGICAL_ROUTING=http://ptesb-qa.telecom.pt:13000/PTP/25_RESOURCE/ResourceNetwork/Services/1.0/getLogicalServiceInfo
# Configurações NETWIN
NETQ_NETWIN_INVENTORY_QUERY_PON=http://ptesb-qa.telecom.pt:13000/PTP/25_RESOURCE/ResourceNetwork/Services/1.0/getONTListPDO
NETQ_NETWIN_INVENTORY_QUERY_PDO=http://ptesb-qa.telecom.pt:13000/PTP/25_RESOURCE/ResourceNetwork/Services/1.0/getPortsPDOUsed
NETQ_NETWIN_INVENTORY_QUERY_ENTERPRISE=http://ptesb-qa.telecom.pt:13000/PTP/25_RESOURCE/ResourceNetwork/Services/3.0/getRequest
NETQ_NETWIN_INVENTORY_QUERY_ENTERPRISE2=http://ptesb-qa.telecom.pt:13000/PTP/25_RESOURCE/ResourceNetwork/Services/2.0/getLogicalServiceInfo
NETQ_NETWIN_INVENTORY_QUERY_ENTERPRISE3=http://ptesb-qa.telecom.pt:13000/PTP/25_RESOURCE/ResourceNetwork/Services/2.0/getResources
NETQ_NETWIN_INVENTORY_ENTERPRISE_UPDATE==http://10.162.125.52:81/ns-jvt-webservice-inv-v1-0/JVTInventory
# Configurações HOMENETWORK
NETQ_HOMENETWORK_URL_HGW_DYNAMIC_IP_QUERY=http://ptesb-qa.telecom.pt:13000/PTP/25_PRODUCT/ProductAdditionalProduct/Services/2.0/getDynamicIP
NETQ_HOMENETWORK_URL_HGW_DYNAMIC_IP_SET=http://ptesb-qa.telecom.pt:13000/PTP/25_PRODUCT/ProductAdditionalProduct/Services/2.0/createDynamicIP
NETQ_HOMENETWORK_URL_HGW_DYNAMIC_IP_UPDATE==http://ptesb-qa.telecom.pt:13000/PTP/25_PRODUCT/ProductAdditionalProduct/Services/2.0/updateDynamicIP
NETQ_HOMENETWORK_voipManagementIp=194.65.37.64/28
NETQ_HOMENETWORK_voipPM_counter_Minutes=60
# Configurações SMS
NETQ_SMS_PLUGIN_IP=10.251.7.250
NETQ_SMS_PLUGIN_PORT=5532
NETQ_SMS_PLUGIN_SYSTEM_ID=3116
NETQ_SMS_PLUGIN_PASSWORD=HQAA3116
NETQ_SMS_PLUGIN_SRC_NUMBER=12666
NETQ_SMS_BIND_TYPE=BIND_TRX
# Configurações HNS
NETQ_INVENTORY_HNS_PLATFORM_URL=https://pre-release.services.bk.sapo.pt/AllotSecureISP-api/v1/
NETQ_INVENTORY_HNS_PLATFORM_TOKEN="ESB Token=01.-SCCaw-yui3aZ2EFx9O4rA"
NETQ_INVENTORY_HNS_PLATFORM_TIMEOUT=180
