SIGNET_SYSTEM_URL=SIGNET.SYSTEM.URL: http://signetinsight-qa-fe.telecom.pt/SIGNAL/default.aspx
MEO_PROSKILL_ENDPOINT=""
HELP.URL=http://10.162.204.126/help/
ABOUT.URL=http://10.162.204.126/contacts
# Configurações JVM/Aplicações
NETQWEBAPP_JAVA_MEMORY_OPTS="-Xmx512M -Xms512M -Xss256K"
IAM_URL="https://iamoss-qa.telecom.pt"
NETQ_FE_SERVICE_NAME=
NETQ_SERVICE_CLIENT_FE=JhvP2187TzCbGDpvofin9Q
NETQ_SERVICE_SECRET_FE=EtQIdye5SBidpEm9D5x4mQ
NETQ_BE_SERVICE_NAME=pode ficar vazio
NETQ_SERVICE_CLIENT_BE=pode ficar vazio
NETQ_SERVICE_SECRET_BE=pode ficar vazio
NETQ_CLIENT_URL_ENDPOINT=https://netq-qa-fe.telecom.pt
# Configurações Databases
NETQ_DB_URL=jdbc:oracle:thin:@//cxq01vmc01-scan.telecom.pt:1565/QNETQV4CP-SRV
NETQ_DB_USERNAME=netq
NETQ_DB_PASSWORD=Netq_QA#_2021
NETQ_DB_POOLSIZE=5
NETQ_DB_MAX_CONN_PARTITION=2
NETQ_DB_MIN_CONN_PARTITION=1
# Configurações Logger
LOGGING_SERVICE_URL=udp:10.18.128.37
LOGGING_SERVICE_PORT=12201
LOGGING_GELF_LEVEL=DEBUG
LOGGING_CONSOLE_LEVEL=DEBUG
LOGGING_LEVEL_PLAY=DEBUG
LOGGING_LEVEL_APPLICATION=DEBUG
LOGGING_LEVEL_NETQ=INFO
LOGGING_LEVEL_HIBERNATE=INFO
LOGGING_LEVEL_HIBERNATE_INTERNAL_ENGINE=WARN
LOGGING_LEVEL_PT=DEBUG
LOGGING_ROOT_LEVEL=WARN
LOGGING_APP_ENVIRONMENT=me-frontend-qa
